# Generated by Django 5.2.8 on 2025-11-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('photo', models.FileField(upload_to='media')),
                ('janr', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('rejissyor', models.CharField(max_length=100)),
                ('muddat', models.CharField(help_text='Format: 2h 10m', max_length=10)),
            ],
        ),
    ]
